### ISSUE TITLE
Authoritative dnsruby repo has been moved from SourceForge to git by the author, Alex Dalitz.

### ISSUE THREAD

**Issue by keithrbennett** [vertis/dnsruby#1]
The authoritative dnsruby repo has been moved from RubyForge to Github by the author, Alex Dalitz.

It's on @alexdalitz's pages, at https://github.com/alexdalitz/dnsruby.

I'd suggest displaying that very prominently on your front page for the project, or possibly removing the repo altogether if there are no variations between the two repos that need to be saved.

**Comment by vertis** [comment]
Yep, will do

**Comment by vertis** [comment]
I've updated the readme. I'll look into deleting the repo after I've confirmed that I can switch out the official repo without trouble.
